### ISSUE TITLE
How to make a brand new image in VS Code?

### ISSUE THREAD

**Issue by ukd1** [sile/pixcil#1]
I've tried making a new file, naming it a `something.png`, picking the correct extension - basically nothing happens. Do you have to start with an existing file?

**Comment by sile** [comment]
Thank you for using the VS Code extension.
As you said, currently there is no way to create a brand new image in VS Code.
However, I've often wanted this feature too. So I'll implement that in the near future (perhaps next week).

**Comment by sile** [comment]
Hi, I figured out that just creating a new PNG file using a built-in VSCode feature was enough as the video below.  

https://user-images.githubusercontent.com/181413/222940839-e4815b96-68f8-4fdf-9e58-357188b864d8.mp4
