### ISSUE TITLE
Layers and animation not working on sile.github.io/pixcil

### ISSUE THREAD

**Issue by ephetic** [sile/pixcil#4]
Nothing appears to happen when toggling the layer or animation modes.  No errors are logged to the console.

**Comment by sile** [comment]
It is somewhat confusing but adjacent vertical regions are treated as layers if the layer flag is enabled (as follows):

https://github.com/user-attachments/assets/93b83450-8b38-4372-9c60-dc8876a36506

Besides, adjacent horizontal regions are treated as animation frames as well:

https://github.com/user-attachments/assets/129701ce-8c65-41d9-a659-32b60a14fbef

**Comment by sile** [comment]
If the above response does not meet your expectations, please provide detailed information about your environment (such as your OS, browser type, and version).

**Comment by ephetic** [comment]
Ahhhh!  I get it.  You removed the layer/frame count fields, so you require drawing in the adjacent region to enable the next frame/layer.  I like it, I just didn't guess it.  Thank you!

**Comment by sile** [comment]
Yes, the behavior has changed since v0.6.0. 
As there are very limited documents available, please feel free to open an issue if you have any questions.
(I'm very glad you're trying out this tool 👍 )
