### ISSUE TITLE
[Feature Request] Option to export animation as strip rather than APNG

### ISSUE THREAD

**Issue by ephetic** [sile/pixcil#5]
Sprite strips/sheets are more widely supported than APNG files by game engines. I haven't even been able to find a tool to convert APNG to a strip. ~~Ideally, there could be a menu toggle for "Export as Strip", then it exports the bottom row as seen in the editor.~~ This seems like it could require two modes of operation/metadata embedding since it needs to have the mode embedded in the metadata to show up in the editor correctly.

**Comment by sile** [comment]
Thank you for your feature request. But, since I am not familiar with "sprite strips/sheets," could you provide a link to its specifications?

> I haven't even been able to find a tool to convert APNG to a strip.

Although the details are still unclear and my opinion may change, I currently prefer the idea of developing a separate conversion tool for that purpose.
(This is because I generally prefer to keep a single tool as simple as possible.)

**Comment by ephetic** [comment]
Perhaps I'm not using the most common name --Wikipedia calls them texture atlases.  This [Löve Wiki](https://www.love2d.org/wiki/Tutorial:Animation) should make it clear, but to summarize here: it's uncommon in 2D games to use separate files for each frame of an animation nor are animated file formats like GIF used, instead, all the frames are tiled in a single image which gets sliced into frames by the game engine when loaded; e.g.

![image](https://github.com/user-attachments/assets/dfa0615f-9a2b-45fc-9063-a37623cad1fd)

A sprite sheet is similar, but has multiple rows, so I think the strip form would work best with Pixcil since it is so close to how the interface already works, i.e. the bottom row is almost already a sprite sheet, e.g. 
<img width="353" alt="image" src="https://github.com/user-attachments/assets/f4b36bcf-e633-4e8a-879b-e6878f7d7a3c">

So the spec is as follows

- A configuration toggle that selects between the existing APNG format and a PNG sprite strip, which would be an N frame W x H animation would be saved as an (N*W) x H PNG comprised of each W x H frame tiled horizontally.
- [OPTIONAL] Allow configurable padding between frame.  This makes sprite sheets easier for humans to inspect, at the expense of a slight hassle loading them in the engine.


From the user's perspective, this change wouldn't change the interface and would only add a single configuration option, so I hope you don't feel it would detract from Pixcil's simplicity.  As a user, its simplicity is that my animation asset is its own project file for a tool built into the IDE with backwards compatible that can live in the repo with the code; otherwise, the content pipeline requires a separate tool, build step, and artifact.

Thank you for your time.

**Comment by ephetic** [comment]
Sorry, I thought of better links to include. 

[aseprite.org/docs/sprite-sheet/](http://aseprite.org/docs/sprite-sheet/)

I also use [piskelapp.com](https://www.piskelapp.com/) but it doesn't have documenation, only the export wizard: 
<img width="401" alt="image" src="https://github.com/user-attachments/assets/2f36085f-a4a4-4947-9acb-cc3d11ebd9b0">

**Comment by sile** [comment]
Thank you for the information!
I will read the details this weekend or later.

**Comment by sile** [comment]
I glanced at texture atlases, and it seems like a good idea to support them in Pixcil (though I'm not 100% sure yet). Since I'm a bit busy right now, I'll try implementing this feature at the end of this month or next month.

> [OPTIONAL] Allow configurable padding between frames.

I also sometimes want to specify padding between frames and layers. I'll consider this feature as well.

**Comment by ephetic** [comment]
Awesome!  Thank you either way!

**Comment by gingerbeardman** [comment]
I used `apng2gif` to convert the APNG to Animated GIF

I installed it through brew on macOS, but it's available for Mac/Linux/Win: https://apng2gif.sourceforge.net

On Playdate, the platform I develop for, I can use the GIF as a "spritesheet" or as they call it "image table". 

We can also have them as a single image with no padding between cells, and a filename such as:
`example-table-32-20.png` for a table of 32x20px frames.

I normally use Piskel, and maintain a build with support for Playdate image table loading with canvas size set by the filename. https://github.com/gingerbeardman/piskel-playdate

**Comment by ephetic** [comment]
I mostly use LÖVE and Defold, neither of which support GIF either.  I did find an old unmaintained user library for LÖVE that supports APNG, but it requires some iffy integrations that might not be allowed on all build targets. I'm also not sure what of the existing animation tooling it's incompatible with.  

I took a look at Playdate tho.  Fun, but kinda pricey.

**Comment by gingerbeardman** [comment]
Playdate is worth every penny, and some (also: it comes with 24 games) 

A game I made for it, YOYOZO, was featured in the ArsTechnica list "Best Games of 2023" alongside Super Mario Wonder, Zelda TotK, Chants of Sennaar, Baldur's Gate 3, etc

Anyway, more export options would be nice :)

**Comment by ephetic** [comment]
That's rad!  Congratulations.  Are the Playdate games playable online or any other platforms?

**Comment by gingerbeardman** [comment]
Thanks!

No, all my games are exclusive to Playdate.

But you can play some of them (the ones I sell on itch) using the Playdate Simulator that comes with the dev kit. The games I sell through the store on the device cannot be played in the Simulator.

**Comment by sile** [comment]
@ephetic Sprite sheet support has been added in #14. Please let me know if you encounter any issues with this feature.

I understand the current UI is somewhat ad hoc and lacks support for padding between frames. However, because I'm currently busy, I will reconsider the entire UI design at the end of this year or the beginning of next year.

**Comment by ephetic** [comment]
Fantastic! Thank you so much. I'll test it tonight.

**Comment by sile** [comment]
👍 

Please note that this feature is currently only available on https://sile.github.io/pixcil/. I plan to release the new version for VSCode after issue #10 is resolved. However, if you need to use the feature via the VSCode extension right now, please let me know.

**Comment by ephetic** [comment]
Hey, I'm going to be doing another game programming meetup in a couple weeks.  If you have time, can you bump the VSC release to include this?  Thank you so much!!!

**Comment by sile** [comment]
Okay 👌 
I will be releasing the new version this weekend.

**Comment by sile** [comment]
[FYI] Just released v0.8.0 (VSC  extension).

**Comment by ephetic** [comment]
Thank you!
