### ISSUE TITLE
Update VSCode Extension Release

### ISSUE THREAD

**Issue by ephetic** [sile/pixcil#7]
I just built and smoke-tested the latest version in VSCode and it appears to work great (MacOS 14.5, M2), but I can't get the built extension loaded outside of the project folder.  Anyway, please add "update release vscode extension" to your todo list.  :)

**Comment by sile** [comment]
Okay. I'll release the latest version of the extension within a few days.
(Since I'm not sure if there are actual users of this extension, I haven't updated the version to reduce maintenance costs.)

**Comment by sile** [comment]
Just published v0.7.0: https://marketplace.visualstudio.com/items?itemName=sile.pixcil

**Comment by ephetic** [comment]
Awesome!  Thank you very much!
