### ISSUE TITLE
[Feature Request] Ability to load frames

### ISSUE THREAD

**Issue by gingerbeardman** [sile/pixcil#9]
This is a cool editor. Thanks for making it.

I notice that it saves APNG format, but it can't load the same file back in? 

So I'd like to request that.

Related, as mentioned in https://github.com/sile/pixcil/issues/5#issuecomment-2273943306, it would also be cool if it could load files with filename matching this pattern `example-table-32-20` for a series of frames of 32x20px. This would make it ideal for Playdate development and more. 

Thanks

**Comment by sile** [comment]
Thank you for reporting this issue. 
I'm not certain, but it seems Pixcil currently only supports loading APNG files generated by Pixcil itself. 
Since supporting general APNG files shouldn't be difficult, I'll attempt to implement this feature over the weekend.

**Comment by gingerbeardman** [comment]
The problem I had is that I had not enabled Animation in settings, so the loading of the APNG silently fails.

After enabling Animation in settings, the APNG I just saved loaded back in just fine.

HTH

**Comment by sile** [comment]
Thank you for the additional information.

> The problem I had is that I had not enabled Animation in settings, so the loading of the APNG silently fails.

Hmm, I was unable to reproduce this behavior using the latest version of Pixcil.
(It could load APNG files generated by Pixcil regardless of the "Animation" setting.)

By the way, I have started implementing support for loading general APNG files in the following branch: https://github.com/sile/pixcil/tree/load-apng
(It will likely take a week or more to complete.)

**Comment by gingerbeardman** [comment]
OK, yes you're right. The problem is something else.

Sometimes loading fails, but if I try again it works. Sometimes!

![pixcil-13082024,_170014](https://github.com/user-attachments/assets/d379fb1f-88b9-43e0-9fcd-bb67484c0114)

https://github.com/user-attachments/assets/28530c95-64e4-49be-9c43-450bd50c8429

**Comment by sile** [comment]
Thank you for sharing the video!
The behavior seems very weird 😖

I was able to reproduce this issue using Safari (I usually use Chrome, which does not have this issue). Therefore, I will investigate it in more detail in the near future.

**Comment by gingerbeardman** [comment]
Thanks, appreciated.

**Comment by sile** [comment]
I have resolved the issue and deployed the fixed version to https://sile.github.io/pixcil.
If you encounter any problems with the latest version, please reopen this issue (you might need to hard reload your browser to use the latest version).

**Comment by gingerbeardman** [comment]
Cheers!
